/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Clase;
import aplicacion.Bono;
import aplicacion.Usuario;
import aplicacion.Actividad;

/**
 *
 * @author hammamboutafant
 */
public class VAdmin extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form VAdmin
     */
    public VAdmin(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        btnAcceder.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        panelCuenta = new javax.swing.JPanel();
        panelBonos = new javax.swing.JPanel();
        buscaIdBono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscaPalabrasClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaBonos = new javax.swing.JTable();
        btnBuscarBono = new javax.swing.JButton();
        checkBonos = new javax.swing.JCheckBox();
        btnNuevoBono = new javax.swing.JButton();
        btnInscribir = new javax.swing.JButton();
        panelClases = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClases = new javax.swing.JTable();
        nueva_clase_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        opciones = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        panelFinanzas = new javax.swing.JPanel();
        panelUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        buscaId = new javax.swing.JTextField();
        buscaNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAcceder = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox();
        Nuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("Cuenta", panelCuenta);

        jLabel3.setText("Id Bono");

        jLabel4.setText("Palabras clave");

        tablaBonos.setModel(new ModeloTablaBonos());
        jScrollPane4.setViewportView(tablaBonos);

        btnBuscarBono.setText("Buscar");
        btnBuscarBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBonoActionPerformed(evt);
            }
        });

        checkBonos.setText("Buscar sólo bonos NO caducados");

        btnNuevoBono.setText("Nuevo Bono");
        btnNuevoBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoBonoActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir socio");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBonosLayout = new javax.swing.GroupLayout(panelBonos);
        panelBonos.setLayout(panelBonosLayout);
        panelBonosLayout.setHorizontalGroup(
            panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBonosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscaIdBono, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(panelBonosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelBonosLayout.createSequentialGroup()
                        .addComponent(checkBonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarBono))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBonosLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnNuevoBono, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscribir)
                .addGap(182, 182, 182))
        );
        panelBonosLayout.setVerticalGroup(
            panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBonosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaIdBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarBono)
                    .addComponent(checkBonos))
                .addGap(30, 30, 30)
                .addGroup(panelBonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoBono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInscribir))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Bonos", panelBonos);

        tablaClases.setModel(new ModeloTablaClases());
        jScrollPane3.setViewportView(tablaClases);

        nueva_clase_btn.setText("Nueva clase");
        nueva_clase_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueva_clase_btnActionPerformed(evt);
            }
        });

        jButton2.setText("Editar clase");

        opciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fecha", "hora_inicio", "plazas", "precio" }));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        jLabel5.setText("Ordenar por");

        javax.swing.GroupLayout panelClasesLayout = new javax.swing.GroupLayout(panelClases);
        panelClases.setLayout(panelClasesLayout);
        panelClasesLayout.setHorizontalGroup(
            panelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClasesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClasesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nueva_clase_btn)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)
                        .addGap(104, 104, 104))
                    .addGroup(panelClasesLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(90, Short.MAX_VALUE))))
        );
        panelClasesLayout.setVerticalGroup(
            panelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClasesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nueva_clase_btn)
                    .addComponent(jButton2)
                    .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37))
        );

        panelPrincipal.addTab("Clases", panelClases);

        javax.swing.GroupLayout panelFinanzasLayout = new javax.swing.GroupLayout(panelFinanzas);
        panelFinanzas.setLayout(panelFinanzasLayout);
        panelFinanzasLayout.setHorizontalGroup(
            panelFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        panelFinanzasLayout.setVerticalGroup(
            panelFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        panelPrincipal.addTab("Finanzas", panelFinanzas);

        tablaUsuarios.setModel(new ModeloTablaUsuarios());
        jScrollPane2.setViewportView(tablaUsuarios);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAcceder.setText("Acceder a usuario");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Socio Normal", "Socio Prémium", "Administrador", "Mantenimiento", "Profesor" }));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAcceder)
                        .addGap(58, 58, 58)
                        .addComponent(Nuevo)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceder)
                    .addComponent(btnBuscar)
                    .addComponent(Nuevo))
                .addGap(35, 35, 35))
        );

        panelPrincipal.addTab("Usuarios", panelUsuarios);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NuevoActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        ModeloTablaUsuarios mtu = (ModeloTablaUsuarios) tablaUsuarios.getModel();
        String idUsuario;
        idUsuario = mtu.obtenerUsuario(tablaUsuarios.getSelectedRow()).getIdUsuario();
        fa.NuevoUsuario(idUsuario);
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ModeloTablaUsuarios m;

        m = (ModeloTablaUsuarios) tablaUsuarios.getModel();/*ModeloTablaLibros extiende a AbstractTableModel*/

        //Guardo en el objeto tabla los resultados obtenidos
        m.setFilas(fa.consultarUsuarios((buscaId.getText().isEmpty()) ? null : buscaId.getText(),
                (buscaNombre.getText().isEmpty()) ? null : buscaNombre.getText(), comboTipo.getSelectedItem().toString()));
        /*Si el campo id está vacío se pone a null*/

        //Si la tabla obtenida tras la búsqueda tiene alguna fila:
        if (m.getRowCount() > 0) {
            tablaUsuarios.setRowSelectionInterval(0, 0);//Por defecto selecciono la fila 0
            btnAcceder.setEnabled(true);
        } else {
            btnAcceder.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBonoActionPerformed
        // TODO add your handling code here:
        ModeloTablaBonos m;

        m = (ModeloTablaBonos) tablaBonos.getModel();/*ModeloTablaLibros extiende a AbstractTableModel*/

        m.setFilas(fa.consultarBonos((buscaIdBono.getText().isEmpty()) ? null : Integer.parseInt(buscaIdBono.getText()),
                (buscaPalabrasClave.getText().isEmpty()) ? null : buscaPalabrasClave.getText(), checkBonos.isSelected()));

        if (m.getRowCount() > 0) {
            tablaBonos.setRowSelectionInterval(0, 0);//Por defecto selecciono la fila 0
            btnInscribir.setEnabled(true);
        }
        else{
            btnInscribir.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarBonoActionPerformed

    private void btnNuevoBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoBonoActionPerformed
        // TODO add your handling code here:
        fa.ventanaNuevoBono();
    }//GEN-LAST:event_btnNuevoBonoActionPerformed

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        // TODO add your handling code here:
        String seleccion = opciones.getSelectedItem().toString();
        cargarClases(seleccion);
    }//GEN-LAST:event_opcionesActionPerformed

    private void nueva_clase_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueva_clase_btnActionPerformed
        // TODO add your handling code here:
        //hallamos los profesores, y los guardamos en un arralist:
        java.util.ArrayList<Usuario> profesores = fa.consultarProfesores();
        java.util.ArrayList<Actividad> actividades = fa.consultarActividades();
        fa.ventanaNuevaClase(profesores, actividades);
    }//GEN-LAST:event_nueva_clase_btnActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        ModeloTablaBonos m = (ModeloTablaBonos) tablaBonos.getModel();/*ModeloTablaLibros extiende a AbstractTableModel*/

        aplicacion.Bono bono = m.obtenerBono(tablaBonos.getSelectedRow());
        fa.ventanaInscripcionBono(bono);
    }//GEN-LAST:event_btnInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarBono;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnNuevoBono;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaId;
    private javax.swing.JTextField buscaIdBono;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JTextField buscaPalabrasClave;
    private javax.swing.JCheckBox checkBonos;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nueva_clase_btn;
    private javax.swing.JComboBox opciones;
    private javax.swing.JPanel panelBonos;
    private javax.swing.JPanel panelClases;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelFinanzas;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTable tablaBonos;
    private javax.swing.JTable tablaClases;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables

    public void cargarClases(String orden) {
        java.util.List<Clase> clases;
        ModeloTablaClases mu = (ModeloTablaClases) tablaClases.getModel();
        clases = fa.consultarClases(orden);
        mu.setFilas(clases);
         if (mu.getRowCount() > 0) {
        tablaClases.setRowSelectionInterval(0, 0);
         }
    }

    public void cargarBonos() {
        java.util.List<Bono> bonos;
        ModeloTablaBonos m = (ModeloTablaBonos) tablaBonos.getModel();
        bonos = fa.consultarBonos(null, null, false);//Realizo una consulta de los bonos sin restricciones
        m.setFilas(bonos);

        if (m.getRowCount() > 0) {
            tablaBonos.setRowSelectionInterval(0, 0);
            btnInscribir.setEnabled(true);
        } else {
            btnInscribir.setEnabled(false);
        }
    }

    public void cargarUsuarios() {
        java.util.List<Usuario> usuarios;
        ModeloTablaUsuarios m = (ModeloTablaUsuarios) tablaUsuarios.getModel();
        usuarios = fa.consultarUsuarios(null, null, null);//Realizo una consulta de los bonos sin restricciones
        m.setFilas(usuarios);
        if (m.getRowCount() > 0) {
            tablaUsuarios.setRowSelectionInterval(0, 0);
            btnAcceder.setEnabled(true);
        } else {
            btnAcceder.setEnabled(false);
        }
    }
}
